### ISSUE TITLE
Where's the discussion for keybase?

### ISSUE THREAD

**Issue by taoeffect** [pfraze/beaker#4]
The README says:

> keybase ([discussion](https://github.com/pfraze/beaker/blob/master/doc/discuss-notes/0001-keybase.md))

But links to a non-discussion. Was that meant to be an issue or a gist?

Also, my two cents: can't seriously call this "decentralization tech" if you're relying on a centralized service for your identity.

Various issues with Keybase:

- It's centralized, and there's no need for it to be
- Verification is very slow
- There are plenty of far better choices, including [DPKI](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/final-documents/dpki.pdf)-type solutions and [CONIKS](https://coniks.cs.princeton.edu)

**Comment by pfraze** [comment]
Greg, please take a friendlier approach to your issues! Maybe this would have come off better in conversation, but the tone was upsetting in text form. I know about the work you've done in this space, so I do appreciate that it means a lot to you.

I'm looking for good and ready solutions. I'm not sold on keybase yet, but the centralization issue is not why. As I mention in the discussion document, keybase would be used as a single identity provider in a federated scheme; users would be addressed `@keybase.io`. Therefore, keybase would not be a centralized solution in the long-term. It would, at worst, be the sole provider in a federated scheme in the short-term. In the future, other providers would be addable, after some more protocol work.

I am currently less interested in keybase than I was previously, though, for the following reasons:

 - Their implementation doesn't look simple to integrate into this codebase
 - (As far as I can tell) They use a novel JS implementation of PGP, that hasn't been well-audited
 - They appear to be limited to only RSA keys, at the moment
 - They've shifted focus away from their key distribution system, with their filesharing tools

That said, their basic approach is reasonable when applied to federated identity. The sigchain system is similar to the Certificate Transparency solution in Google's End-to-End, and I think that's a promising idea. Signed merkle-logs allow users to gossip p2p about identity provider responses and enforce honesty. (The identity proofs on twitter/hn/reddit/etc seem like a clever but temporary hack, that's only relevant prior to a federated CT deployment.)

I'll give your links a detailed read. If you want to expand on them, please do. This is an active topic, so your input will be appreciated.

**Comment by taoeffect** [comment]
> Greg, please take a friendlier approach to your issues! Maybe this would have come off better in conversation, but the tone was upsetting in text form. 

Woah, please explain, what was upsetting?

Also, not clear to me what the answer to the original question is (where's the discussion? is this it?)

**Comment by pfraze** [comment]
If you'd like to continue discussing decorum, you can email me (pfrazee@gmail.com). Let's not bog down the issues board with it.

To answer your original question, the link is correct, but the discussion is not finished.

**Comment by pfraze** [comment]
Closing for now. Keybase is not the final decision. Feel free to open new issues to discuss other options!
