### ISSUE TITLE
PouchDB over Websql

### ISSUE THREAD

**Issue by genecyber** [pfraze/beaker#6]
I did quite a bit of research into databases for the browser and ultimately settled on pouchdb. It works in the browser, has gracefull fallback to whichever database the browser supports. It also has lots of plugins and is couch DB compatible. I was even table to make a serializer to convert my entire database into a json object and encrypt and export / import. You can see it in action here: http://wallet.ribbit.me/app

New accounts are disabled but if you do an import and fail to import, refresh the page and you will be logged in to a brand new account. Use the email/password you started with to "unlock it" 

You can take a look at the database stuff by typing me.data into the console.

**Comment by pfraze** [comment]
I disagree on this. PouchDB is good, but SQLite has better features for aggregate queries, full-text-search, and joins.
